version: "3"
services:
  nodejs-website:
#    image: ubuntu:latest
    image: nodejs/express
    container_name: nodejs-website
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - nodejs-mongodb
    volumes:
      - ./project:/project


  nodejs-mongodb:
    image: mongo:latest
    container_name: nodejs-mongodb
    restart: always
    environment:
#      - MONGO_INITDB_ROOT_USERNAME="admin"
#      - MONGO_INITDB_ROOT_PASSWORD="password"
#      - MONGO_INITDB_DATABASE="blog-website"
      - MONGODB_USER="admin"
      - MONGODB_PASS="password"
      - MONGODB_DATABASE="blog-website"
    ports:
      - 27017:27017
    volumes:
        - ./mongodb:/data/db


  nodejs-mongoadmin:
    image: mongo-express:latest
    container_name: nodejs-mongoadmin
    depends_on:
      - nodejs-mongodb
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_DATABASE="blog-website"
      - ME_CONFIG_MONGODB_ADMINUSERNAME="admin"
      - ME_CONFIG_MONGODB_ADMINPASSWORD="password"
      - ME_CONFIG_MONGODB_URL="mongodb://nodejs-mongodb:27017"
