version: "3"
services:
  nodejs-website:
#    image: ubuntu:latest
    image: nodejs/express
    container_name: nodejs-website
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - nodejs-mysqldb
    volumes:
      - ./project:/project:Z
    networks:
      nodejs-bridge:
        ipv4_address: 174.25.192.101

  nodejs-mysqldb:
    image: mariadb
#    build: ./mariadb/Dockerfile
    container_name: nodejs-mysqldb
    expose:
      - "3306"
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
      - ./db/etc/mysql/mariadb.conf.d:/etc/mysql/mariadb.conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      nodejs-bridge:
        ipv4_address: 174.25.192.132

  nodejs-phpmyadmin:
    image: phpmyadmin:5.0.2
    container_name: nodejs-phpmyadmin
    ports:
      - "8088:80"
    depends_on:
      - nodejs-mysqldb
    environment:
      - PMA_HOSTS=174.25.192.132
    volumes:
      - ./phpmyadmin/var/www/html/config.inc.php:/var/www/html/config.inc.php
    networks:
      nodejs-bridge:
        ipv4_address: 174.25.192.199

networks:
  nodejs-bridge:
#    external: true
    driver: bridge
    name: "nodejs-bridge"
    ipam:
      config:
        - subnet: 174.25.192.0/24